ALTER TABLE `SLIMBEAR`.`cart` 
CHANGE COLUMN `uid` `uid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ;

ALTER TABLE `SLIMBEAR`.`category` 
CHANGE COLUMN `uid` `uid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ;

ALTER TABLE `SLIMBEAR`.`coupon` 
CHANGE COLUMN `uid` `uid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ;

ALTER TABLE `SLIMBEAR`.`faq` 
CHANGE COLUMN `uid` `uid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ;

ALTER TABLE `SLIMBEAR`.`inquiry` 
CHANGE COLUMN `uid` `uid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ;

ALTER TABLE `SLIMBEAR`.`inquiryAnswer` 
CHANGE COLUMN `uid` `uid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ;

ALTER TABLE `SLIMBEAR`.`memberCoupon` 
CHANGE COLUMN `uid` `uid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ;

ALTER TABLE `SLIMBEAR`.`memberOrderAddress` 
CHANGE COLUMN `uid` `uid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ;

ALTER TABLE `SLIMBEAR`.`notice` 
CHANGE COLUMN `uid` `uid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ;

ALTER TABLE `SLIMBEAR`.`product` 
CHANGE COLUMN `uid` `uid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ;

ALTER TABLE `SLIMBEAR`.`productBannerTop` 
CHANGE COLUMN `uid` `uid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ;

ALTER TABLE `SLIMBEAR`.`productOrder` 
CHANGE COLUMN `uid` `uid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ;

ALTER TABLE `SLIMBEAR`.`reviewComent` 
CHANGE COLUMN `uid` `uid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ;

ALTER TABLE `SLIMBEAR`.`productReview` 
CHANGE COLUMN `uid` `uid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ;

ALTER TABLE `SLIMBEAR`.`wish` 
CHANGE COLUMN `uid` `uid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ;